### Create User
POST http://localhost:8080/api/users/v1/create
Content-Type: application/json

{
  "name": "User A",
  "email": "usera@mail.com",
  "country": "KH"
}

### Find by id
GET http://localhost:8080/api/users/v1/find/{{id}}
Accept: application/json

### Find by country
GET http://localhost:8080/api/users/v1/country/{{name}}
Accept: application/json

### Find All
GET http://localhost:8080/api/users/v1/all
Accept: application/json

### Delete by id
GET http://localhost:8080/api/users/v1/delete/{{id}}
Accept: application/json



