name: Deploy to App Engine from Source

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    environment: DEV
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build App
        run: mvn clean package -DskipTests

      - name: Deploy to App Engine
        id: deploy
        run: gcloud app deploy ${{ github.workspace }}/target/springboot3gcp-0.0.1-SNAPSHOT.jar