name: Deploy Project to App Engine

on:
  push:
    branches: [ "main" ]
    tags: ["v*"]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    environment: DEV
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: 'Checkout'
        name: Checkout Repo
        uses: actions/checkout@v3

      - id: 'auth'
        name: Authenticate with GCP
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - id: 'deploy'
        name: Deploy JAVA project
        uses: 'google-github-actions/deploy-appengine@v1'
        with:
          deliverables: ${{ github.workspace }}/src/main/appengine/app.yaml

      # Example of using the output
      - id: 'test'
        run: 'curl "${{ steps.deploy.outputs.url }}"'